server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-MGT-SERVICE
          predicates:
            - Path=/account/**, /accounts/**, /customer/**, /customers/**
          filters:
            - name: AuthenticationFilter

        - id: transaction-service
          uri: lb://TRANSACTION-MGT-SERVICE
          predicates:
            - Path=/transaction/**
          filters:
            - name: AuthenticationFilter

        - id: mortgage-service
          uri: lb://MORTGAGE-MGT-SERVICE
          predicates:
            - Path=/api/mortgage/**
          filters:
            - name: AuthenticationFilter

        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
